// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicaIdProto {
    #[prost(string, tag = "1")]
    pub group_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LogIdProto {
    #[prost(uint64, tag = "1")]
    pub index: u64,
    #[prost(uint64, tag = "2")]
    pub term: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntryProto {
    #[prost(message, optional, tag = "1")]
    pub log_id: ::core::option::Option<LogIdProto>,
    #[prost(uint64, tag = "2")]
    pub check_sum: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResponseError {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendEntriesReq {
    #[prost(message, optional, tag = "1")]
    pub target_id: ::core::option::Option<ReplicaIdProto>,
    #[prost(message, optional, tag = "2")]
    pub primary: ::core::option::Option<ReplicaIdProto>,
    #[prost(uint64, tag = "3")]
    pub version: u64,
    #[prost(uint64, tag = "4")]
    pub term: u64,
    #[prost(message, optional, tag = "5")]
    pub prev_log: ::core::option::Option<LogIdProto>,
    #[prost(uint64, tag = "6")]
    pub committed_log_index: u64,
    #[prost(message, repeated, tag = "7")]
    pub entries: ::prost::alloc::vec::Vec<LogEntryProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppendEntriesRep {
    #[prost(message, optional, tag = "1")]
    pub error: ::core::option::Option<ResponseError>,
    #[prost(uint64, tag = "2")]
    pub term: u64,
    #[prost(uint64, tag = "3")]
    pub last_log_index: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstallSnapshotReq {
    #[prost(message, optional, tag = "1")]
    pub target_id: ::core::option::Option<ReplicaIdProto>,
    #[prost(message, optional, tag = "2")]
    pub primary: ::core::option::Option<ReplicaIdProto>,
    #[prost(uint64, tag = "3")]
    pub version: u64,
    #[prost(uint64, tag = "4")]
    pub term: u64,
    #[prost(message, optional, tag = "5")]
    pub snapshot_log_id: ::core::option::Option<LogIdProto>,
    #[prost(uint64, tag = "6")]
    pub reader_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstallSnapshotRep {
    #[prost(message, optional, tag = "1")]
    pub error: ::core::option::Option<ResponseError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicaRecoverReq {
    #[prost(message, optional, tag = "1")]
    pub target_id: ::core::option::Option<ReplicaIdProto>,
    #[prost(message, optional, tag = "2")]
    pub recover_id: ::core::option::Option<ReplicaIdProto>,
    #[prost(uint64, tag = "3")]
    pub version: u64,
    #[prost(uint64, tag = "4")]
    pub term: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicaRecoverRep {
    #[prost(message, optional, tag = "1")]
    pub error: ::core::option::Option<ResponseError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferPrimaryReq {
    #[prost(message, optional, tag = "1")]
    pub target_id: ::core::option::Option<ReplicaIdProto>,
    #[prost(message, optional, tag = "2")]
    pub new_primary: ::core::option::Option<ReplicaIdProto>,
    #[prost(uint64, tag = "3")]
    pub version: u64,
    #[prost(uint64, tag = "4")]
    pub term: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferPrimaryRep {
    #[prost(message, optional, tag = "1")]
    pub error: ::core::option::Option<ResponseError>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFileReq {
    #[prost(message, optional, tag = "1")]
    pub target_id: ::core::option::Option<ReplicaIdProto>,
    #[prost(uint64, tag = "2")]
    pub reader_id: u64,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub offset: u64,
    #[prost(uint64, tag = "5")]
    pub count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFileRep {
    #[prost(message, optional, tag = "1")]
    pub error: ::core::option::Option<ResponseError>,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub eof: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcResponse {
    #[prost(message, optional, tag = "1")]
    pub error: ::core::option::Option<ResponseError>,
    #[prost(oneof = "rpc_response::Response", tags = "2, 3, 4, 5, 6")]
    pub response: ::core::option::Option<rpc_response::Response>,
}
/// Nested message and enum types in `RpcResponse`.
pub mod rpc_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "2")]
        AppendEntriesRep(super::AppendEntriesRep),
        #[prost(message, tag = "3")]
        InstallSnapshotRep(super::InstallSnapshotRep),
        #[prost(message, tag = "4")]
        ReplicaRecoverRep(super::ReplicaRecoverRep),
        #[prost(message, tag = "5")]
        TransferPrimaryRep(super::TransferPrimaryRep),
        #[prost(message, tag = "6")]
        GetFileRep(super::GetFileRep),
    }
}
/// Generated client implementations.
pub mod pacifica_g_rpc_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PacificaGRpcClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PacificaGRpcClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PacificaGRpcClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PacificaGRpcClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PacificaGRpcClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn append_entries(
            &mut self,
            request: impl tonic::IntoRequest<super::AppendEntriesReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pacifica.PacificaGRpc/AppendEntries",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pacifica.PacificaGRpc", "AppendEntries"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn install_snapshot(
            &mut self,
            request: impl tonic::IntoRequest<super::InstallSnapshotReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pacifica.PacificaGRpc/InstallSnapshot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pacifica.PacificaGRpc", "InstallSnapshot"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn replica_recover(
            &mut self,
            request: impl tonic::IntoRequest<super::ReplicaRecoverReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pacifica.PacificaGRpc/ReplicaRecover",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pacifica.PacificaGRpc", "ReplicaRecover"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn transfer_primary(
            &mut self,
            request: impl tonic::IntoRequest<super::TransferPrimaryReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pacifica.PacificaGRpc/TransferPrimary",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pacifica.PacificaGRpc", "TransferPrimary"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_file(
            &mut self,
            request: impl tonic::IntoRequest<super::GetFileReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pacifica.PacificaGRpc/GetFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pacifica.PacificaGRpc", "GetFile"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod pacifica_g_rpc_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PacificaGRpcServer.
    #[async_trait]
    pub trait PacificaGRpc: std::marker::Send + std::marker::Sync + 'static {
        async fn append_entries(
            &self,
            request: tonic::Request<super::AppendEntriesReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status>;
        async fn install_snapshot(
            &self,
            request: tonic::Request<super::InstallSnapshotReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status>;
        async fn replica_recover(
            &self,
            request: tonic::Request<super::ReplicaRecoverReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status>;
        async fn transfer_primary(
            &self,
            request: tonic::Request<super::TransferPrimaryReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status>;
        async fn get_file(
            &self,
            request: tonic::Request<super::GetFileReq>,
        ) -> std::result::Result<tonic::Response<super::RpcResponse>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct PacificaGRpcServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PacificaGRpcServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PacificaGRpcServer<T>
    where
        T: PacificaGRpc,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/pacifica.PacificaGRpc/AppendEntries" => {
                    #[allow(non_camel_case_types)]
                    struct AppendEntriesSvc<T: PacificaGRpc>(pub Arc<T>);
                    impl<
                        T: PacificaGRpc,
                    > tonic::server::UnaryService<super::AppendEntriesReq>
                    for AppendEntriesSvc<T> {
                        type Response = super::RpcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AppendEntriesReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PacificaGRpc>::append_entries(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AppendEntriesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pacifica.PacificaGRpc/InstallSnapshot" => {
                    #[allow(non_camel_case_types)]
                    struct InstallSnapshotSvc<T: PacificaGRpc>(pub Arc<T>);
                    impl<
                        T: PacificaGRpc,
                    > tonic::server::UnaryService<super::InstallSnapshotReq>
                    for InstallSnapshotSvc<T> {
                        type Response = super::RpcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InstallSnapshotReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PacificaGRpc>::install_snapshot(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InstallSnapshotSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pacifica.PacificaGRpc/ReplicaRecover" => {
                    #[allow(non_camel_case_types)]
                    struct ReplicaRecoverSvc<T: PacificaGRpc>(pub Arc<T>);
                    impl<
                        T: PacificaGRpc,
                    > tonic::server::UnaryService<super::ReplicaRecoverReq>
                    for ReplicaRecoverSvc<T> {
                        type Response = super::RpcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReplicaRecoverReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PacificaGRpc>::replica_recover(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReplicaRecoverSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pacifica.PacificaGRpc/TransferPrimary" => {
                    #[allow(non_camel_case_types)]
                    struct TransferPrimarySvc<T: PacificaGRpc>(pub Arc<T>);
                    impl<
                        T: PacificaGRpc,
                    > tonic::server::UnaryService<super::TransferPrimaryReq>
                    for TransferPrimarySvc<T> {
                        type Response = super::RpcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TransferPrimaryReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PacificaGRpc>::transfer_primary(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TransferPrimarySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pacifica.PacificaGRpc/GetFile" => {
                    #[allow(non_camel_case_types)]
                    struct GetFileSvc<T: PacificaGRpc>(pub Arc<T>);
                    impl<T: PacificaGRpc> tonic::server::UnaryService<super::GetFileReq>
                    for GetFileSvc<T> {
                        type Response = super::RpcResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetFileReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PacificaGRpc>::get_file(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PacificaGRpcServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "pacifica.PacificaGRpc";
    impl<T> tonic::server::NamedService for PacificaGRpcServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
